plugins {
    id 'maven-publish'
    id 'dev.ultreon.photon' version '0.2.0'
    id 'org.jetbrains.kotlin.jvm'
}

photon {
    production = true
    modProject = project

    // Set your properties in the gradle.properties file
    projectName = property("mod_displayName")
    projectVersion = property("mod_version")
    projectGroup = property("mod_group")
    projectId = property("mod_name")
    javaVersion = 21
}

group = photon.projectGroup
version = photon.projectVersion

base {
    archivesName = photon.projectId
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    quantum photon.client(property("versions_quantum").toString())

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    implementation 'net.fabricmc:fabric-language-kotlin:1.9.0+kotlin.1.8.0', {
        exclude group: 'net.fabricmc', module: 'fabric-loader' // We depend on a custom version of the fabric loader here
    }
}

test {
    useJUnitPlatform()
}

processResources {
    filesMatching('fabric.mod.json') {
        expand(project.properties)
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }

    repositories {
        mavenLocal()

        // Add your repository here
        // maven { url "https://myrepo.example.com/releases" }
    }
}
kotlin {
    jvmToolchain(21)
}
